apiVersion: v1
kind: Service
metadata:
  name: temperaturas-srv-https
  labels:
    app: temperaturas
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: temperaturas
    tier: frontend
  ports:
  - protocol: TCP
    port: 443
    targetPort: 3001
