apiVersion: v1
kind: Service
metadata:
  name: temperaturas-backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: temperaturas-backend
---
apiVersion: v1
kind: Service
metadata:
  name: temperaturas-srv
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: temperaturas-frontend
