apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperaturas-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temperaturas-frontend
  template:
    metadata:
      labels:
        app: temperaturas-frontend
    spec:
      containers:
      - name: temperaturas-frontend
        image: mm98zgz/temperaturas-frontend:v2
        ports:
        - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperaturas-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperaturas-backend
  template:
    metadata:
      labels:
        app: temperaturas-backend
    spec:
      containers:
      - name: temperaturas-backend
        image: mm98zgz/temperaturas-backend:v1
        ports:
        - containerPort: 5000
