apiVersion: v1
kind: Service
metadata:
  name: temperaturas-backend
  labels:
    app: temperaturas
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: temperaturas
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: temperaturas-srv
  labels:
    app: temperaturas
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: temperaturas
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
